name: Create a comment

on:
  issues:
    types: [opened]

jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github contet"
        run: echo "${{toJSON(github.event)}}" | jq
        shell: bash
        
